name: pcd-car-app  # Nombre del proyecto de la aplicación

services:
  # Servicio de Frontend
  ui:
    image: pcd-car-ui-image:latest  # Nombre y etiqueta de la imagen que se generará o usará
    container_name: pcd-car-ui-container  # Nombre asignado al contenedor
    build:
      context: ./UI  # Carpeta que contiene los archivos para construir la imagen del frontend
      dockerfile: Dockerfile  # Nombre del Dockerfile, relativo al contexto especificado
    ports:
      - "8501:8501"  # Mapea el puerto 8501 del host al puerto 8501 del contenedor
    depends_on:
      - model  # Garantiza que el contenedor 'model' (backend) se levante antes que el frontend
    networks:
      - pcd-car-network  # Conecta este servicio a la red definida
    volumes:
      - ./data:/code/data 

  # Servicio de Backend
  model:
    image: pcd-car-model-image:latest  # Nombre y etiqueta de la imagen que se generará o usará para el backend
    container_name: pcd-car-model-container  # Nombre asignado al contenedor backend
    build:
      context: ./model  # Carpeta que contiene los archivos para construir la imagen del backend
      dockerfile: Dockerfile  # Nombre del Dockerfile, relativo al contexto especificado
    ports:
      - "8000:8000"  # Mapea el puerto 8000 del host al puerto 8000 del contenedor
    networks:
      - pcd-car-network  # Conecta este servicio a la red definida
    volumes:
      - ./data:/code/data 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://pcd-car-model-container:8000/predict"]
      interval: 30s
      timeout: 10s
      retries: 5


# Definición de redes
networks:
  pcd-car-network:  # Nombre de la red que comparten los servicios
    name: pcd-car-network-1  # Nombre específico de la red
    driver: bridge  # El tipo de red, 'bridge' permite la comunicación interna entre los contenedores